NEW Install dynamodb if required

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -193,11 +193,10 @@ jobs:
           fi
           echo "PHP has been configured"
 
-      - name: Apt install additional requirements 
+      - name: Install additional requirements 
         env:
           GITHUB_REPOSITORY: ${{ github.repository }}
         run: |
-          # apt install extra requirements as required
           if [[ "${{ matrix.endtoend }}" == "true" ]]; then
             sudo apt install -y software-properties-common
             sudo add-apt-repository -y ppa:ondrej/php
@@ -208,6 +207,30 @@ jobs:
           fi
           if [[ $GITHUB_REPOSITORY =~ /(silverstripe-spellcheck|recipe-authoring-tools)$ ]] || [[ "${{ matrix.phpunit_suite }}" == "recipe-authoring-tools" ]]; then
             sudo apt install -y hunspell libhunspell-dev hunspell-en-us
+          fi
+          if [[ $GITHUB_REPOSITORY =~ /(silverstripe-dynamodb)$ ]]; then
+            # install dynamodb
+            mkdir _dynamodb
+            cd _dynamodb
+            sudo wget https://s3.ap-southeast-1.amazonaws.com/dynamodb-local-singapore/dynamodb_local_latest.tar.gz
+            sudo tar -xf dynamodb_local_latest.tar.gz
+            # run dynamo db as background process
+            # java openjdk 11 is pre-installed
+            $(java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar) &
+            for i in {1..10}; do
+              if ! [[ $(ps -aux | grep DynamoDBLocal.jar) =~ DynamoDBLocal_lib ]]; then
+                if [[ $i == 10 ]]; then
+                  echo "dynamodb failed to start"
+                  exit 1
+                fi
+                echo "Waiting for dynamodb to start"
+                sleep 1
+              else
+                echo "dynamodb has started"
+                break
+              fi
+            done
+            cd -
           fi
 
       - name: Configure apache - endtoend test
@@ -530,6 +553,7 @@ jobs:
       - name: Final preparation
         env:
           GITHUB_WORKSPACE: ${{ github.workspace }}
+          GITHUB_REPOSITORY: ${{ github.repository }}
         run: |
           # Add .env file and create artifacts directory
           # Note: the wonky indentation is intentional so there is no space at the start of
@@ -569,6 +593,16 @@ jobs:
           SS_MFA_SECRET_KEY="1234567894175b99966561e1efe237e4"
           SS_BASE_URL="http://localhost"
           EOF
+
+          if [[ $GITHUB_REPOSITORY =~ /(silverstripe-dynamodb)$ ]]; then
+            cat << EOF >> .env
+          AWS_DYNAMODB_ENDPOINT="http://localhost:8000"
+          AWS_DYNAMODB_SESSION_TABLE=mysession
+          AWS_ACCESS_KEY=my-access-key
+          AWS_SECRET_KEY=my-secret
+          AWS_REGION_NAME=ap-southeast-2
+          EOF
+          fi
 
           # debug
           echo ".env is"
